In [1]:
import scanpy as scanpy
import numpy as np # linear algebra
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
de_train = pd.read_parquet('../data/de_train.parquet')
adata_train = pd.read_parquet('../data/adata_train.parquet')

In [9]:
adata_obs_meta = pd.read_csv('../data/adata_obs_meta.csv')

id_map = pd.read_csv('../data/id_map.csv')

multiome_obs_meta = pd.read_csv('../data/multiome_obs_meta.csv')

multiome_var_meta = pd.read_csv('../data/multiome_var_meta.csv')

In [10]:
adata_train

                     obs_id        gene  count  normalized_count
0          000006a87ba75b72        AATF      1          5.567933
1          000006a87ba75b72      ABHD12      1          5.567933
2          000006a87ba75b72       ABHD3      1          5.567933
3          000006a87ba75b72  AC004687.1      1          5.567933
4          000006a87ba75b72  AC009779.2      1          5.567933
...                     ...         ...    ...               ...
416442307  ffffe67500d95d8d      ZSWIM7      1          4.205181
416442308  ffffe67500d95d8d      ZSWIM8      1          4.205181
416442309  ffffe67500d95d8d        ZUP1      1          4.205181
416442310  ffffe67500d95d8d        ZXDB      1          4.205181
416442311  ffffe67500d95d8d         ZYX      4          5.580224

[416442312 rows x 4 columns]

In [14]:
adata_obs_meta

,obs_id,library_id,plate_name,well,row,col,cell_id,donor_id,cell_type,sm_lincs_id,sm_name,SMILES,dose_uM,timepoint_hr,control
0,000006a87ba75b72,library_4,plate_4,F7,F,7,PBMC,donor_2,T cells CD4+,LSM-4944,MLN 2238,CC(C)C[C@H](NC(=O)CNC(=O)c1cc(Cl)ccc1Cl)B(O)O,1.0,24,False
1,0000233976e3cd37,library_0,plate_3,D4,D,4,PBMC,donor_1,T cells CD4+,LSM-46203,BMS-265246,CCCCOc1c(C(=O)c2c(F)cc(C)cc2F)cnc2[nH]ncc12,1.0,24,False
2,0001533c5e876362,library_2,plate_0,B11,B,11,PBMC,donor_0,T regulatory cells,LSM-45663,Resminostat,CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1,1.0,24,False
3,00022f989630d14b,library_35,plate_2,E6,E,6,PBMC,donor_0,T cells CD4+,LSM-43216,FK 866,O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1,1.0,24,False
4,0002560bd38ce03e,library_22,plate_4,B6,B,6,PBMC,donor_2,T cells CD4+,LSM-1099,Nilotinib,Cc1cn(-c2cc(NC(=O)c3ccc(C)c(Nc4nccc(-c5cccnc5)...,1.0,24,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240085,ffff28f274e983df,library_27,plate_0,G12,G,12,PBMC,donor_0,NK cells,LSM-3349,Mometasone Furoate,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,1.0,24,False
240086,ffff32893af5befb,library_31,plate_4,E7,E,7,PBMC,donor_2,T cells CD4+,LSM-2287,Midostaurin,CO[C@@H]1[C@H](N(C)C(=O)c2ccccc2)C[C@H]2O[C@]1...,1.0,24,False
240087,ffff6c3e0a7b05ad,library_38,plate_1,C5,C,5,PBMC,donor_2,NK cells,LSM-45786,BAY 87-2243,Cc1cc(-c2nc(-c3ccc(OC(F)(F)F)cc3)no2)nn1Cc1ccn...,1.0,24,False
240088,ffff8e571c7e8cb0,library_28,plate_5,B1,B,1,PBMC,donor_1,B cells,LSM-43181,Belinostat,O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO,0.1,24,True
240089,ffffe67500d95d8d,library_9,plate_3,E1,E,1,PBMC,donor_1,Myeloid cells,LSM-43181,Belinostat,O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO,0.1,24,True